<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="XSD">
      <schema location="http://inkaban3ua-eai05:8000/soa-infra/services/CRMASYNC/CCRMOM_OrderRequestValidatorStub/EAI.MSG.CCRM.OM.138_OrderRequest.xsd"/>
      <rootElement name="orderRequest" namespace="http://www.reuters.com/ns/2007/01/25/GCAP/EAI/CCRM/OM/OrderManagement"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="XSD">
      <schema location="http://inkaban3ua-eai05:8000/soa-infra/services/CRMASYNC/CCRMOM_OrderRequestValidatorStub/EAI.MSG.CCRM.OM.138_OrderRequest.xsd"/>
      <rootElement name="orderRequest" namespace="http://www.reuters.com/ns/2007/01/25/GCAP/EAI/CCRM/OM/OrderManagement"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.4.0(build 110106.1932.5682) AT [TUE MAR 13 13:22:26 GMT+05:30 2012]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:ns0="http://www.reuters.com/ns/2007/09/01/GCAP/SchemaAnnotations"
                xmlns:ns2="http://www.reuters.com/ns/2007/09/01/GCAP/CommonUserTypes"
                xmlns:bpel2="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:cmt="http://www.reuters.com/ns/2007/09/01/GCAP/CommonMessageTypes"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:orcl="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:xsdLocal="http://www.reuters.com/ns/2007/01/25/GCAP/EAI/CCRM/OM/OrderManagement"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:comt="http://www.reuters.com/ns/2007/09/01/GCAP/CommonOrderTypes"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:ns1="http://www.reuters.com/ns/2007/09/01/GCAP/CommonAccountTypes"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                xmlns:ehdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.esb.server.headers.ESBHeaderFunctions"
                exclude-result-prefixes="xsi xsl ns0 ns2 cmt xsdLocal comt xsd ns1 xp20 bpws bpel2 bpm ora socket mhdr orcl dvm hwf med ids xdk xref ldap">
  <xsl:template match="/">
    <xsdLocal:orderRequest>
      <xsdLocal:eaiHeader>
        <cmt:applicationId>
          <xsl:value-of select="/xsdLocal:orderRequest/xsdLocal:eaiHeader/cmt:applicationId"/>
        </cmt:applicationId>
        <cmt:transactionId>
          <xsl:value-of select="/xsdLocal:orderRequest/xsdLocal:eaiHeader/cmt:transactionId"/>
        </cmt:transactionId>
        <cmt:messageId>
          <xsl:value-of select="/xsdLocal:orderRequest/xsdLocal:eaiHeader/cmt:messageId"/>
        </cmt:messageId>
        <cmt:messageHistory>
          <xsl:value-of select="/xsdLocal:orderRequest/xsdLocal:eaiHeader/cmt:messageHistory"/>
        </cmt:messageHistory>
        <cmt:tracingId>
          <xsl:value-of select="/xsdLocal:orderRequest/xsdLocal:eaiHeader/cmt:tracingId"/>
        </cmt:tracingId>
        <cmt:timeStamp>
          <xsl:value-of select="/xsdLocal:orderRequest/xsdLocal:eaiHeader/cmt:timeStamp"/>
        </cmt:timeStamp>
        <cmt:instanceId>
          <xsl:value-of select="/xsdLocal:orderRequest/xsdLocal:eaiHeader/cmt:instanceId"/>
        </cmt:instanceId>
        <cmt:timeToLive>
          <xsl:value-of select="/xsdLocal:orderRequest/xsdLocal:eaiHeader/cmt:timeToLive"/>
        </cmt:timeToLive>
        <cmt:payloadVersion>
          <xsl:value-of select="/xsdLocal:orderRequest/xsdLocal:eaiHeader/cmt:payloadVersion"/>
        </cmt:payloadVersion>
      </xsdLocal:eaiHeader>
      <xsdLocal:logicalCountry>
        <xsl:value-of select="/xsdLocal:orderRequest/xsdLocal:logicalCountry"/>
      </xsdLocal:logicalCountry>
      <xsdLocal:messageHeader>
        <comt:actionCode>
          <xsl:value-of select="/xsdLocal:orderRequest/xsdLocal:messageHeader/comt:actionCode"/>
        </comt:actionCode>
        <comt:version>
          <xsl:value-of select="/xsdLocal:orderRequest/xsdLocal:messageHeader/comt:version"/>
        </comt:version>
        <comt:userId>
          <xsl:value-of select="/xsdLocal:orderRequest/xsdLocal:messageHeader/comt:userId"/>
        </comt:userId>
      </xsdLocal:messageHeader>
      <xsdLocal:orderHeader>
        <comt:CRMOrderNumber>
          <xsl:value-of select="/xsdLocal:orderRequest/xsdLocal:orderHeader/comt:CRMOrderNumber"/>
        </comt:CRMOrderNumber>
        <comt:AAATransactionId>
          <xsl:value-of select="/xsdLocal:orderRequest/xsdLocal:orderHeader/comt:AAATransactionId"/>
        </comt:AAATransactionId>
        <comt:installDate>
          <xsl:value-of select="/xsdLocal:orderRequest/xsdLocal:orderHeader/comt:installDate"/>
        </comt:installDate>
        <comt:removalDate>
          <xsl:value-of select="/xsdLocal:orderRequest/xsdLocal:orderHeader/comt:removalDate"/>
        </comt:removalDate>
        <comt:orderNote>
          <xsl:value-of select="/xsdLocal:orderRequest/xsdLocal:orderHeader/comt:orderNote"/>
        </comt:orderNote>
        <comt:orderStatus>
          <xsl:value-of select="/xsdLocal:orderRequest/xsdLocal:orderHeader/comt:orderStatus"/>
        </comt:orderStatus>
        <comt:phone>
          <xsl:value-of select="/xsdLocal:orderRequest/xsdLocal:orderHeader/comt:phone"/>
        </comt:phone>
        <comt:OMSlastName>
          <xsl:value-of select="/xsdLocal:orderRequest/xsdLocal:orderHeader/comt:OMSlastName"/>
        </comt:OMSlastName>
        <comt:OMSfirstName>
          <xsl:value-of select="/xsdLocal:orderRequest/xsdLocal:orderHeader/comt:OMSfirstName"/>
        </comt:OMSfirstName>
        <comt:email>
          <xsl:value-of select="/xsdLocal:orderRequest/xsdLocal:orderHeader/comt:email"/>
        </comt:email>
        <comt:businessCase>
          <xsl:value-of select="/xsdLocal:orderRequest/xsdLocal:orderHeader/comt:businessCase"/>
        </comt:businessCase>
        <comt:accountLocId>
          <xsl:value-of select="/xsdLocal:orderRequest/xsdLocal:orderHeader/comt:accountLocId"/>
        </comt:accountLocId>
        <comt:technicalOrderNo>
          <xsl:value-of select="/xsdLocal:orderRequest/xsdLocal:orderHeader/comt:technicalOrderNo"/>
        </comt:technicalOrderNo>
        <comt:technicalOrderOwner>
          <xsl:value-of select="/xsdLocal:orderRequest/xsdLocal:orderHeader/comt:technicalOrderOwner"/>
        </comt:technicalOrderOwner>
        <comt:technicalFulfilmentStatusReason>
          <xsl:value-of select="/xsdLocal:orderRequest/xsdLocal:orderHeader/comt:technicalFulfilmentStatusReason"/>
        </comt:technicalFulfilmentStatusReason>
        <comt:technicalFulfilmentStatus>
          <xsl:value-of select="/xsdLocal:orderRequest/xsdLocal:orderHeader/comt:technicalFulfilmentStatus"/>
        </comt:technicalFulfilmentStatus>
        <comt:plannedInstallDate>
          <xsl:value-of select="/xsdLocal:orderRequest/xsdLocal:orderHeader/comt:plannedInstallDate"/>
        </comt:plannedInstallDate>
        <comt:poNumber>
          <xsl:value-of select="/xsdLocal:orderRequest/xsdLocal:orderHeader/comt:poNumber"/>
        </comt:poNumber>
        <comt:custRequiredDate>
          <xsl:value-of select="/xsdLocal:orderRequest/xsdLocal:orderHeader/comt:custRequiredDate"/>
        </comt:custRequiredDate>
        <comt:actualInstallationDate>
          <xsl:value-of select="/xsdLocal:orderRequest/xsdLocal:orderHeader/comt:actualInstallationDate"/>
        </comt:actualInstallationDate>
        <comt:account>
          <xsl:value-of select="/xsdLocal:orderRequest/xsdLocal:orderHeader/comt:account"/>
        </comt:account>
        <comt:accountLocation>
          <xsl:value-of select="/xsdLocal:orderRequest/xsdLocal:orderHeader/comt:accountLocation"/>
        </comt:accountLocation>
        <comt:orderType>
          <xsl:value-of select="/xsdLocal:orderRequest/xsdLocal:orderHeader/comt:orderType"/>
        </comt:orderType>
        <xsl:for-each select="/xsdLocal:orderRequest/xsdLocal:orderHeader/comt:quoteNote">
          <comt:quoteNote>
            <comt:type>
              <xsl:value-of select="comt:type"/>
            </comt:type>
            <comt:noteId>
              <xsl:value-of select="comt:noteId"/>
            </comt:noteId>
            <comt:installationNotes>
              <xsl:value-of select="comt:installationNotes"/>
            </comt:installationNotes>
          </comt:quoteNote>
        </xsl:for-each>
        <comt:quoteNumber>
          <xsl:value-of select="/xsdLocal:orderRequest/xsdLocal:orderHeader/comt:quoteNumber"/>
        </comt:quoteNumber>
        <comt:quoteRevisionNumber>
          <xsl:value-of select="/xsdLocal:orderRequest/xsdLocal:orderHeader/comt:quoteRevisionNumber"/>
        </comt:quoteRevisionNumber>
        <comt:assignedOMS>
          <xsl:value-of select="/xsdLocal:orderRequest/xsdLocal:orderHeader/comt:assignedOMS"/>
        </comt:assignedOMS>
        <comt:salesSpecialist>
          <xsl:value-of select="/xsdLocal:orderRequest/xsdLocal:orderHeader/comt:salesSpecialist"/>
        </comt:salesSpecialist>
        <comt:currencyCode>
          <xsl:value-of select="/xsdLocal:orderRequest/xsdLocal:orderHeader/comt:currencyCode"/>
        </comt:currencyCode>
        <comt:accountManager>
          <xsl:value-of select="/xsdLocal:orderRequest/xsdLocal:orderHeader/comt:accountManager"/>
        </comt:accountManager>
        <comt:targetSystem>
          <xsl:value-of select="/xsdLocal:orderRequest/xsdLocal:orderHeader/comt:targetSystem"/>
        </comt:targetSystem>
        <comt:expectedTRTMDate>
          <xsl:value-of select="/xsdLocal:orderRequest/xsdLocal:orderHeader/comt:expectedTRTMDate"/>
        </comt:expectedTRTMDate>
        <comt:orderOwner>
          <xsl:value-of select="/xsdLocal:orderRequest/xsdLocal:orderHeader/comt:orderOwner"/>
        </comt:orderOwner>
        <comt:RCRMField1>
          <xsl:value-of select="/xsdLocal:orderRequest/xsdLocal:orderHeader/comt:RCRMField1"/>
        </comt:RCRMField1>
        <comt:SoldToAccountNumber>
          <xsl:value-of select="/xsdLocal:orderRequest/xsdLocal:orderHeader/comt:SoldToAccountNumber"/>
        </comt:SoldToAccountNumber>
        <comt:RCRMField6>
          <xsl:value-of select="/xsdLocal:orderRequest/xsdLocal:orderHeader/comt:RCRMField6"/>
        </comt:RCRMField6>
        <comt:RCRMField7>
          <xsl:value-of select="/xsdLocal:orderRequest/xsdLocal:orderHeader/comt:RCRMField7"/>
        </comt:RCRMField7>
        <comt:RCRMSAPConCountry>
          <xsl:value-of select="/xsdLocal:orderRequest/xsdLocal:orderHeader/comt:RCRMSAPConCountry"/>
        </comt:RCRMSAPConCountry>
      </xsdLocal:orderHeader>
      <xsl:for-each select="/xsdLocal:orderRequest/xsdLocal:orderLineItem">
        <xsdLocal:orderLineItem>
          <comt:CRMOLIId>
            <xsl:value-of select="comt:CRMOLIId"/>
          </comt:CRMOLIId>
          <comt:rootItemId>
            <xsl:value-of select="comt:rootItemId"/>
          </comt:rootItemId>
          <comt:parentOrderItemId>
            <xsl:value-of select="comt:parentOrderItemId"/>
          </comt:parentOrderItemId>
          <comt:actionCode>
            <xsl:value-of select="comt:actionCode"/>
          </comt:actionCode>
          <comt:businessCase>
            <xsl:value-of select="comt:businessCase"/>
          </comt:businessCase>
          <comt:salesCode>
            <xsl:value-of select="comt:salesCode"/>
          </comt:salesCode>
          <comt:billToSubscriberNumber>
            <xsl:value-of select="comt:billToSubscriberNumber"/>
          </comt:billToSubscriberNumber>
          <comt:billToSubAccountNumber>
            <xsl:value-of select="comt:billToSubAccountNumber"/>
          </comt:billToSubAccountNumber>
          <comt:PLI>
            <xsl:value-of select="comt:PLI"/>
          </comt:PLI>
          <comt:productIntegrationId>
            <xsl:value-of select="comt:productIntegrationId"/>
          </comt:productIntegrationId>
          <comt:permissioningSystem>
            <xsl:value-of select="comt:permissioningSystem"/>
          </comt:permissioningSystem>
          <comt:manualPermissioningRequired>
            <xsl:value-of select="comt:manualPermissioningRequired"/>
          </comt:manualPermissioningRequired>
          <comt:AKR>
            <xsl:value-of select="comt:AKR"/>
          </comt:AKR>
          <comt:userID>
            <xsl:value-of select="comt:userID"/>
          </comt:userID>
          <comt:userIDType>
            <xsl:value-of select="comt:userIDType"/>
          </comt:userIDType>
          <comt:userNumber>
            <xsl:value-of select="comt:userNumber"/>
          </comt:userNumber>
          <comt:firstName>
            <xsl:value-of select="comt:firstName"/>
          </comt:firstName>
          <comt:lastname>
            <xsl:value-of select="comt:lastname"/>
          </comt:lastname>
          <comt:dob>
            <xsl:value-of select="comt:dob"/>
          </comt:dob>
          <comt:isNewUser>
            <xsl:value-of select="comt:isNewUser"/>
          </comt:isNewUser>
          <comt:QUID>
            <xsl:value-of select="comt:QUID"/>
          </comt:QUID>
          <comt:installDate>
            <xsl:value-of select="comt:installDate"/>
          </comt:installDate>
          <comt:removalDate>
            <xsl:value-of select="comt:removalDate"/>
          </comt:removalDate>
          <comt:discount>
            <xsl:value-of select="comt:discount"/>
          </comt:discount>
          <comt:specialPrice>
            <xsl:value-of select="comt:specialPrice"/>
          </comt:specialPrice>
          <comt:specialPriceCurr>
            <xsl:value-of select="comt:specialPriceCurr"/>
          </comt:specialPriceCurr>
          <comt:specialPriceRestrictionDate>
            <xsl:value-of select="comt:specialPriceRestrictionDate"/>
          </comt:specialPriceRestrictionDate>
          <comt:itemNumber>
            <xsl:value-of select="comt:itemNumber"/>
          </comt:itemNumber>
          <comt:startStopBillingDate>
            <xsl:value-of select="comt:startStopBillingDate"/>
          </comt:startStopBillingDate>
          <comt:billingType>
            <xsl:value-of select="comt:billingType"/>
          </comt:billingType>
          <comt:billingNote>
            <xsl:value-of select="comt:billingNote"/>
          </comt:billingNote>
          <comt:freeTrailFlag>
            <xsl:value-of select="comt:freeTrailFlag"/>
          </comt:freeTrailFlag>
          <comt:freeTrailEndDate>
            <xsl:value-of select="comt:freeTrailEndDate"/>
          </comt:freeTrailEndDate>
          <comt:STB>
            <xsl:value-of select="comt:STB"/>
          </comt:STB>
          <comt:assetIntegrationId>
            <xsl:value-of select="comt:assetIntegrationId"/>
          </comt:assetIntegrationId>
          <comt:orderLineStatus>
            <xsl:value-of select="comt:orderLineStatus"/>
          </comt:orderLineStatus>
          <comt:permissioningStatus>
            <xsl:value-of select="comt:permissioningStatus"/>
          </comt:permissioningStatus>
          <comt:interfaceForBilling>
            <xsl:value-of select="comt:interfaceForBilling"/>
          </comt:interfaceForBilling>
          <comt:interfaceForFulfilment>
            <xsl:value-of select="comt:interfaceForFulfilment"/>
          </comt:interfaceForFulfilment>
          <xsl:for-each select="comt:configuredAttribute">
            <comt:configuredAttribute>
              <comt:attributeName>
                <xsl:value-of select="comt:attributeName"/>
              </comt:attributeName>
              <comt:value>
                <xsl:value-of select="comt:value"/>
              </comt:value>
              <comt:attributeIntegrationId>
                <xsl:value-of select="comt:attributeIntegrationId"/>
              </comt:attributeIntegrationId>
              <comt:valueIntegrationId>
                <xsl:value-of select="comt:valueIntegrationId"/>
              </comt:valueIntegrationId>
            </comt:configuredAttribute>
          </xsl:for-each>
          <comt:technicalFulfilmentReq>
            <xsl:value-of select="comt:technicalFulfilmentReq"/>
          </comt:technicalFulfilmentReq>
          <comt:technicalApprovalReq>
            <xsl:value-of select="comt:technicalApprovalReq"/>
          </comt:technicalApprovalReq>
          <comt:fulfilmentStatus>
            <xsl:value-of select="comt:fulfilmentStatus"/>
          </comt:fulfilmentStatus>
          <comt:fulfilmentIntegrationFlag>
            <xsl:value-of select="comt:fulfilmentIntegrationFlag"/>
          </comt:fulfilmentIntegrationFlag>
          <comt:billingAccountId>
            <xsl:value-of select="comt:billingAccountId"/>
          </comt:billingAccountId>
          <comt:technicalFulfilmentFlag>
            <xsl:value-of select="comt:technicalFulfilmentFlag"/>
          </comt:technicalFulfilmentFlag>
          <comt:quantity>
            <xsl:value-of select="comt:quantity"/>
          </comt:quantity>
          <comt:product>
            <xsl:value-of select="comt:product"/>
          </comt:product>
          <comt:altInstalBillingId>
            <xsl:value-of select="comt:altInstalBillingId"/>
          </comt:altInstalBillingId>
          <comt:freeTrialDuration>
            <xsl:value-of select="comt:freeTrialDuration"/>
          </comt:freeTrialDuration>
          <comt:freeTrialStartDate>
            <xsl:value-of select="comt:freeTrialStartDate"/>
          </comt:freeTrialStartDate>
          <comt:lastUpdateDate>
            <xsl:value-of select="comt:lastUpdateDate"/>
          </comt:lastUpdateDate>
          <comt:mandatorytechFulfilmentFlag>
            <xsl:value-of select="comt:mandatorytechFulfilmentFlag"/>
          </comt:mandatorytechFulfilmentFlag>
          <comt:technicalVettingFlag>
            <xsl:value-of select="comt:technicalVettingFlag"/>
          </comt:technicalVettingFlag>
          <comt:WorkPhone>
            <xsl:value-of select="comt:WorkPhone"/>
          </comt:WorkPhone>
          <comt:ResponseCode>
            <xsl:value-of select="comt:ResponseCode"/>
          </comt:ResponseCode>
          <comt:RCRMePlatformId>
            <xsl:value-of select="comt:RCRMePlatformId"/>
          </comt:RCRMePlatformId>
          <comt:RCRMSupportLanguage>
            <xsl:value-of select="comt:RCRMSupportLanguage"/>
          </comt:RCRMSupportLanguage>
          <comt:RCRMSegGrpEndUserActivity>
            <xsl:value-of select="comt:RCRMSegGrpEndUserActivity"/>
          </comt:RCRMSegGrpEndUserActivity>
          <comt:RCRMRegionalFocus>
            <xsl:value-of select="comt:RCRMRegionalFocus"/>
          </comt:RCRMRegionalFocus>
          <comt:RCRMMarketingConsentSetDate>
            <xsl:value-of select="comt:RCRMMarketingConsentSetDate"/>
          </comt:RCRMMarketingConsentSetDate>
          <comt:RCRMManualPermissionedFlag>
            <xsl:value-of select="comt:RCRMManualPermissionedFlag"/>
          </comt:RCRMManualPermissionedFlag>
          <comt:RCRMLocalLastName>
            <xsl:value-of select="comt:RCRMLocalLastName"/>
          </comt:RCRMLocalLastName>
          <comt:RCRMLocalFirstName>
            <xsl:value-of select="comt:RCRMLocalFirstName"/>
          </comt:RCRMLocalFirstName>
          <comt:RCRMLocalDACSId>
            <xsl:value-of select="comt:RCRMLocalDACSId"/>
          </comt:RCRMLocalDACSId>
          <comt:RCRMLegalConsentSetDate>
            <xsl:value-of select="comt:RCRMLegalConsentSetDate"/>
          </comt:RCRMLegalConsentSetDate>
          <comt:RCRMLegalConsent>
            <xsl:value-of select="comt:RCRMLegalConsent"/>
          </comt:RCRMLegalConsent>
          <comt:RCRMLastUpdatedProfileDate>
            <xsl:value-of select="comt:RCRMLastUpdatedProfileDate"/>
          </comt:RCRMLastUpdatedProfileDate>
          <comt:RCRMFTLFlagSetDate>
            <xsl:value-of select="comt:RCRMFTLFlagSetDate"/>
          </comt:RCRMFTLFlagSetDate>
          <comt:RCRMFTLCompleteFlag>
            <xsl:value-of select="comt:RCRMFTLCompleteFlag"/>
          </comt:RCRMFTLCompleteFlag>
          <comt:RCRMErrorContext>
            <xsl:value-of select="comt:RCRMErrorContext"/>
          </comt:RCRMErrorContext>
          <comt:RCRMErrorCode>
            <xsl:value-of select="comt:RCRMErrorCode"/>
          </comt:RCRMErrorCode>
          <comt:RCRMDiscountReason>
            <xsl:value-of select="comt:RCRMDiscountReason"/>
          </comt:RCRMDiscountReason>
          <comt:RCRMDirectMarketing>
            <xsl:value-of select="comt:RCRMDirectMarketing"/>
          </comt:RCRMDirectMarketing>
          <comt:RCRMCPfGTempURL>
            <xsl:value-of select="comt:RCRMCPfGTempURL"/>
          </comt:RCRMCPfGTempURL>
          <comt:RCRMBillingAccount>
            <xsl:value-of select="comt:RCRMBillingAccount"/>
          </comt:RCRMBillingAccount>
          <comt:RCRMActionCode>
            <xsl:value-of select="comt:RCRMActionCode"/>
          </comt:RCRMActionCode>
          <comt:RCRMAAAUpdatedProfileDate>
            <xsl:value-of select="comt:RCRMAAAUpdatedProfileDate"/>
          </comt:RCRMAAAUpdatedProfileDate>
          <comt:PrimaryAccountId>
            <xsl:value-of select="comt:PrimaryAccountId"/>
          </comt:PrimaryAccountId>
          <comt:ParentOrderItemId>
            <xsl:value-of select="comt:parentOrderItemId"/>
          </comt:ParentOrderItemId>
          <comt:ModId>
            <xsl:value-of select="comt:ModId"/>
          </comt:ModId>
          <comt:MM>
            <xsl:value-of select="comt:MM"/>
          </comt:MM>
          <comt:EmailAddress>
            <xsl:value-of select="comt:EmailAddress"/>
          </comt:EmailAddress>
          <comt:ILA>
            <xsl:value-of select="comt:ILA"/>
          </comt:ILA>
          <comt:contactMarketFocus>
            <xsl:value-of select="comt:contactMarketFocus"/>
          </comt:contactMarketFocus>
          <comt:billingPlatform>
            <xsl:value-of select="comt:billingPlatform"/>
          </comt:billingPlatform>
          <!--           <comt:extraInfo>
              <xsl:copy-of select="orcl:get-content-as-string(comt:MxPDBName)"/>
          </comt:extraInfo>-->
          <comt:MxPDBName>
            <xsl:copy-of select="orcl:get-content-as-string(comt:MxPDBName)"/>
          </comt:MxPDBName>
          <comt:umbrellaProductIntegrationId>
            <xsl:value-of select="comt:umbrellaProductIntegrationId"/>
          </comt:umbrellaProductIntegrationId>
          <comt:contactReutersMessagingId>
            <xsl:value-of select="comt:contactReutersMessagingId"/>
          </comt:contactReutersMessagingId>
          <comt:oldContactUserId>
            <xsl:value-of select="comt:oldContactUserId"/>
          </comt:oldContactUserId>
          <comt:CpfgErrorMessage>
            <xsl:value-of select="comt:CpfgErrorMessage"/>
          </comt:CpfgErrorMessage>
          <comt:installSubscriberNumber>
            <xsl:value-of select="comt:installSubscriberNumber"/>
          </comt:installSubscriberNumber>
          <comt:installSubscriberAccountId>
            <xsl:value-of select="comt:installSubscriberAccountId"/>
          </comt:installSubscriberAccountId>
          <comt:installSubAccountNumber>
            <xsl:value-of select="comt:installSubAccountNumber"/>
          </comt:installSubAccountNumber>
          <comt:installLocationAccountId>
            <xsl:value-of select="comt:installLocationAccountId"/>
          </comt:installLocationAccountId>
          <comt:ContactId>
            <xsl:value-of select="comt:ContactId"/>
          </comt:ContactId>
          <comt:userGroup>
            <xsl:value-of select="comt:userGroup"/>
          </comt:userGroup>
          <comt:userDomain>
            <xsl:value-of select="comt:userDomain"/>
          </comt:userDomain>
          <comt:serverId>
            <xsl:value-of select="comt:serverId"/>
          </comt:serverId>
          <comt:contactJobFunction>
            <xsl:value-of select="comt:contactJobFunction"/>
          </comt:contactJobFunction>
          <comt:contactAnonymityReason>
            <xsl:value-of select="comt:contactAnonymityReason"/>
          </comt:contactAnonymityReason>
          <comt:contactAnonymityFlag>
            <xsl:value-of select="comt:contactAnonymityFlag"/>
          </comt:contactAnonymityFlag>
          <comt:isDelete>
            <xsl:value-of select="comt:isDelete"/>
          </comt:isDelete>
          <comt:netPriceDisplay>
            <xsl:value-of select="comt:netPriceDisplay"/>
          </comt:netPriceDisplay>
          <comt:creditDebit>
            <xsl:value-of select="comt:creditDebit"/>
          </comt:creditDebit>
          <comt:SAPBillable>
            <xsl:value-of select="comt:SAPBillable"/>
          </comt:SAPBillable>
          <comt:SAPItemNumber>
            <xsl:value-of select="comt:SAPItemNumber"/>
          </comt:SAPItemNumber>
          <comt:PONumber>
            <xsl:value-of select="comt:PONumber"/>
          </comt:PONumber>
          <comt:InstallLocationAccountNumber>
            <xsl:value-of select="comt:InstallLocationAccountNumber"/>
          </comt:InstallLocationAccountNumber>
          <comt:BillToAccountNumber>
            <xsl:value-of select="comt:BillToAccountNumber"/>
          </comt:BillToAccountNumber>
          <comt:RCRMField2>
            <xsl:value-of select="comt:RCRMField2"/>
          </comt:RCRMField2>
          <comt:RCRMField3>
            <xsl:value-of select="comt:RCRMField3"/>
          </comt:RCRMField3>
          <comt:SAPOrderNumber>
            <xsl:value-of select="comt:SAPOrderNumber"/>
          </comt:SAPOrderNumber>
          <comt:RCRMField6>
            <xsl:value-of select="comt:RCRMField6"/>
          </comt:RCRMField6>
          <comt:RCRMField1>
            <xsl:value-of select="comt:RCRMField1"/>
          </comt:RCRMField1>
          <comt:RCRMField10>
            <xsl:value-of select="comt:RCRMField10"/>
          </comt:RCRMField10>
          <comt:SAPActionCode>
            <xsl:value-of select="comt:SAPActionCode"/>
          </comt:SAPActionCode>
          <comt:SAPBusinessCase>
            <xsl:value-of select="comt:SAPBusinessCase"/>
          </comt:SAPBusinessCase>
          <comt:CalculatedListPrice>
            <xsl:value-of select="comt:CalculatedListPrice"/>
          </comt:CalculatedListPrice>
          <comt:ListPrice>
            <xsl:value-of select="comt:ListPrice"/>
          </comt:ListPrice>
          <comt:BillingPeriod>
            <xsl:value-of select="comt:BillingPeriod"/>
          </comt:BillingPeriod>
          <comt:PublishContactToSAP>
            <xsl:value-of select="comt:PublishContactToSAP"/>
          </comt:PublishContactToSAP>
          <comt:ContactStatus>
            <xsl:value-of select="comt:ContactStatus"/>
          </comt:ContactStatus>
          <comt:PPLId>
            <xsl:value-of select="comt:PPLId"/>
          </comt:PPLId>
          <comt:primaryUUID>
            <xsl:value-of select="comt:primaryUUID"/>
          </comt:primaryUUID>
        </xsdLocal:orderLineItem>
      </xsl:for-each>
    </xsdLocal:orderRequest>
  </xsl:template>
</xsl:stylesheet>
