<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="XSD">
      <schema location="EAI.MSG.CCRM.OM.148_OrderRequest.xsd"/>
      <rootElement name="OrderRequest" namespace="http://www.siebel.com/xml/RCRM%20Order%20Entry"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="XSD">
      <schema location="EAI.MSG.CCRM.OM.138_OrderRequest.xsd"/>
      <rootElement name="orderRequest" namespace="http://www.reuters.com/ns/2007/01/25/GCAP/EAI/CCRM/OM/OrderManagement"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.3.0(build 100415.2045.2557) AT [TUE JAN 10 10:40:02 IST 2012]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:ns3="http://www.reuters.com/ns/2007/09/01/GCAP/CommonUserTypes"
                xmlns:ns1="http://www.reuters.com/ns/2007/09/01/GCAP/SchemaAnnotations"
                xmlns:bpel2="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:cmt="http://www.reuters.com/ns/2007/09/01/GCAP/CommonMessageTypes"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:orcl="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:xsdLocal="http://www.siebel.com/xml/RCRM%20Order%20Entry"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:ns0="http://www.reuters.com/ns/2007/01/25/GCAP/EAI/CCRM/OM/OrderManagement"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:comt="http://www.reuters.com/ns/2007/09/01/GCAP/CommonOrderTypes"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:ns2="http://www.reuters.com/ns/2007/09/01/GCAP/CommonAccountTypes"
                xmlns:ehdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.esb.server.headers.ESBHeaderFunctions"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl xsdLocal xsd ns3 ns1 cmt ns0 comt ns2 xp20 bpws bpel2 bpm ora socket mhdr orcl dvm hwf med ids xdk xref ldap">
  <xsl:template match="/">
    <ns0:orderRequest>
      <ns0:eaiHeader>
        <cmt:applicationId>
          <xsl:value-of select="/xsdLocal:OrderRequest/xsdLocal:SourceSystem"/>
        </cmt:applicationId>
        <cmt:transactionId>
          <xsl:value-of select="/xsdLocal:OrderRequest/xsdLocal:MessageId"/>
        </cmt:transactionId>
        <cmt:messageId>
          <xsl:value-of select="/xsdLocal:OrderRequest/xsdLocal:MessageId"/>
        </cmt:messageId>
        <cmt:messageHistory>
          <xsl:value-of select='concat(/xsdLocal:OrderRequest/xsdLocal:MessageHistory,";EAI;")'/>
        </cmt:messageHistory>
        <cmt:tracingId>
          <xsl:value-of select="/xsdLocal:OrderRequest/xsdLocal:MessageId"/>
        </cmt:tracingId>
        <cmt:timeStamp>
          <xsl:value-of select="xp20:current-dateTime()"/>
        </cmt:timeStamp>
        <cmt:instanceId>
          <xsl:value-of select='string("0")'/>
        </cmt:instanceId>
        <cmt:timeToLive>
          <xsl:value-of select='number("0")'/>
        </cmt:timeToLive>
        <cmt:payloadVersion>
          <xsl:value-of select='string("A")'/>
        </cmt:payloadVersion>
      </ns0:eaiHeader>
      <ns0:logicalCountry>
        <xsl:value-of select="/xsdLocal:OrderRequest/xsdLocal:OrderEntry-Orders/xsdLocal:PrimaryAccountCountry"/>
      </ns0:logicalCountry>
      <ns0:messageHeader>
        <comt:actionCode>
          <xsl:value-of select="/xsdLocal:OrderRequest/xsdLocal:ActionCode"/>
        </comt:actionCode>
        <comt:version>
          <xsl:value-of select='string("A")'/>
        </comt:version>
        <comt:userId>
          <xsl:value-of select="/xsdLocal:OrderRequest/xsdLocal:UserId"/>
        </comt:userId>
      </ns0:messageHeader>
      <ns0:orderHeader>
        <comt:CRMOrderNumber>
          <xsl:value-of select="/xsdLocal:OrderRequest/xsdLocal:OrderEntry-Orders/xsdLocal:OrderNumber"/>
        </comt:CRMOrderNumber>
        <comt:AAATransactionId>
          <xsl:value-of select="/xsdLocal:OrderRequest/xsdLocal:OrderEntry-Orders/xsdLocal:RCRMTransactionId"/>
        </comt:AAATransactionId>
        <xsl:choose>
          <xsl:when test='orcl:right-trim(/xsdLocal:OrderRequest/xsdLocal:OrderEntry-Orders/xsdLocal:RCRMLIInstallDate) != ""'>
            <comt:installDate>
              <xsl:value-of select='concat(substring(/xsdLocal:OrderRequest/xsdLocal:OrderEntry-Orders/xsdLocal:RCRMLIInstallDate,7.0,4.0),"-",substring(/xsdLocal:OrderRequest/xsdLocal:OrderEntry-Orders/xsdLocal:RCRMLIInstallDate,1.0,2.0),"-",substring(/xsdLocal:OrderRequest/xsdLocal:OrderEntry-Orders/xsdLocal:RCRMLIInstallDate,4.0,2.0))'/>
            </comt:installDate>
          </xsl:when>
          <xsl:otherwise>
            <comt:installDate>
              <xsl:value-of select="/xsdLocal:OrderRequest/xsdLocal:OrderEntry-Orders/xsdLocal:RCRMLIInstallDate"/>
            </comt:installDate>
          </xsl:otherwise>
        </xsl:choose>
        <xsl:choose>
          <xsl:when test='orcl:right-trim(/xsdLocal:OrderRequest/xsdLocal:OrderEntry-Orders/xsdLocal:RCRMLIRemovalDate) != ""'>
            <comt:removalDate>
              <xsl:value-of select='concat(substring(/xsdLocal:OrderRequest/xsdLocal:OrderEntry-Orders/xsdLocal:RCRMLIRemovalDate,7.0,4.0),"-",substring(/xsdLocal:OrderRequest/xsdLocal:OrderEntry-Orders/xsdLocal:RCRMLIRemovalDate,1.0,2.0),"-",substring(/xsdLocal:OrderRequest/xsdLocal:OrderEntry-Orders/xsdLocal:RCRMLIRemovalDate,4.0,2.0))'/>
            </comt:removalDate>
          </xsl:when>
          <xsl:otherwise>
            <comt:removalDate>
              <xsl:value-of select="/xsdLocal:OrderRequest/xsdLocal:OrderEntry-Orders/xsdLocal:RCRMLIRemovalDate"/>
            </comt:removalDate>
          </xsl:otherwise>
        </xsl:choose>
        <comt:orderNote>
          <xsl:value-of select='string("")'/>
        </comt:orderNote>
        <comt:orderStatus>
          <xsl:value-of select="/xsdLocal:OrderRequest/xsdLocal:OrderEntry-Orders/xsdLocal:Status"/>
        </comt:orderStatus>
        <comt:phone>
          <xsl:value-of select="/xsdLocal:OrderRequest/xsdLocal:OrderEntry-Orders/xsdLocal:RCRMOMSPhone"/>
        </comt:phone>
        <comt:OMSlastName>
          <xsl:value-of select="/xsdLocal:OrderRequest/xsdLocal:OrderEntry-Orders/xsdLocal:RCRMOMSLastName"/>
        </comt:OMSlastName>
        <comt:OMSfirstName>
          <xsl:value-of select="/xsdLocal:OrderRequest/xsdLocal:OrderEntry-Orders/xsdLocal:RCRMOMSFirstName"/>
        </comt:OMSfirstName>
        <comt:email>
          <xsl:value-of select="/xsdLocal:OrderRequest/xsdLocal:OrderEntry-Orders/xsdLocal:RCRMOMSEmail"/>
        </comt:email>
        <!--  <comt:field5>
          <xsl:value-of select="/xsdLocal:OrderRequest/xsdLocal:OrderEntry-Orders/xsdLocal:RCRMField5"/>
        </comt:field5>
        <comt:field4>
          <xsl:value-of select="/xsdLocal:OrderRequest/xsdLocal:OrderEntry-Orders/xsdLocal:RCRMField4"/>
        </comt:field4>
        <comt:field3>
          <xsl:value-of select="/xsdLocal:OrderRequest/xsdLocal:OrderEntry-Orders/xsdLocal:RCRMField3"/>
        </comt:field3>-->
        <comt:businessCase>
          <xsl:value-of select="/xsdLocal:OrderRequest/xsdLocal:OrderEntry-Orders/xsdLocal:RCRMBusinessCase"/>
        </comt:businessCase>
        <comt:accountLocId>
          <xsl:value-of select="/xsdLocal:OrderRequest/xsdLocal:OrderEntry-Orders/xsdLocal:RCRMAccountLocId"/>
        </comt:accountLocId>
        <comt:technicalOrderNo>
          <xsl:value-of select="/xsdLocal:OrderRequest/xsdLocal:OrderEntry-Orders/xsdLocal:RCRMTechnicalOrderNo"/>
        </comt:technicalOrderNo>
        <comt:technicalOrderOwner>
          <xsl:value-of select="/xsdLocal:OrderRequest/xsdLocal:OrderEntry-Orders/xsdLocal:RCRMTechOrderOwner"/>
        </comt:technicalOrderOwner>
        <comt:technicalFulfilmentStatusReason>
          <xsl:value-of select="/xsdLocal:OrderRequest/xsdLocal:OrderEntry-Orders/xsdLocal:RCRMTechFulfillmentStatusReason"/>
        </comt:technicalFulfilmentStatusReason>
        <comt:technicalFulfilmentStatus>
          <xsl:value-of select="/xsdLocal:OrderRequest/xsdLocal:OrderEntry-Orders/xsdLocal:Status"/>
        </comt:technicalFulfilmentStatus>
        <comt:plannedInstallDate>
          <xsl:value-of select="/xsdLocal:OrderRequest/xsdLocal:OrderEntry-Orders/xsdLocal:RCRMPlannedInstallDate"/>
        </comt:plannedInstallDate>
        <comt:poNumber>
          <xsl:value-of select="/xsdLocal:OrderRequest/xsdLocal:OrderEntry-Orders/xsdLocal:RCRMPONumber"/>
        </comt:poNumber>
        <comt:custRequiredDate>
          <xsl:value-of select="/xsdLocal:OrderRequest/xsdLocal:OrderEntry-Orders/xsdLocal:RCRMCustRequiredDate"/>
        </comt:custRequiredDate>
        <comt:actualInstallationDate>
          <xsl:value-of select="/xsdLocal:OrderRequest/xsdLocal:OrderEntry-Orders/xsdLocal:OrderEntry-LineItems/xsdLocal:RCRMActualInstallationDate"/>
        </comt:actualInstallationDate>
        <comt:account>
          <xsl:value-of select="/xsdLocal:OrderRequest/xsdLocal:OrderEntry-Orders/xsdLocal:Account"/>
        </comt:account>
        <comt:accountLocation>
          <xsl:value-of select="/xsdLocal:OrderRequest/xsdLocal:OrderEntry-Orders/xsdLocal:AccountLocation"/>
        </comt:accountLocation>
        <comt:orderType>
          <xsl:value-of select="/xsdLocal:OrderRequest/xsdLocal:OrderEntry-Orders/xsdLocal:RCRMNewOrderType"/>
        </comt:orderType>
        <xsl:for-each select="/xsdLocal:OrderRequest/xsdLocal:OrderEntry-Orders/xsdLocal:QuoteNote">
          <comt:quoteNote>
            <comt:type>
              <xsl:value-of select="xsdLocal:RCRMType"/>
            </comt:type>
            <comt:noteId>
              <xsl:value-of select="xsdLocal:NoteId"/>
            </comt:noteId>
            <comt:installationNotes>
              <xsl:value-of select="xsdLocal:InstallationNotes"/>
            </comt:installationNotes>
          </comt:quoteNote>
        </xsl:for-each>
        <comt:quoteNumber>
          <xsl:value-of select="/xsdLocal:OrderRequest/xsdLocal:OrderEntry-Orders/xsdLocal:QuoteNumber"/>
        </comt:quoteNumber>
        <comt:quoteRevisionNumber>
          <xsl:value-of select="/xsdLocal:OrderRequest/xsdLocal:OrderEntry-Orders/xsdLocal:RCRMQuoteRevisionNumber"/>
        </comt:quoteRevisionNumber>
        <comt:assignedOMS>
          <xsl:value-of select="/xsdLocal:OrderRequest/xsdLocal:OrderEntry-Orders/xsdLocal:RCRMAssignedOMS"/>
        </comt:assignedOMS>
        <comt:salesSpecialist>
          <xsl:value-of select="/xsdLocal:OrderRequest/xsdLocal:OrderEntry-Orders/xsdLocal:SalesSpecialist"/>
        </comt:salesSpecialist>
        <comt:currencyCode>
          <xsl:value-of select="/xsdLocal:OrderRequest/xsdLocal:OrderEntry-Orders/xsdLocal:CurrencyCode"/>
        </comt:currencyCode>
        <comt:accountManager>
          <xsl:value-of select="/xsdLocal:OrderRequest/xsdLocal:OrderEntry-Orders/xsdLocal:AccountManager"/>
        </comt:accountManager>
        <comt:targetSystem>
          <xsl:value-of select="/xsdLocal:OrderRequest/xsdLocal:TargetSystem"/>
        </comt:targetSystem>
        <comt:expectedTRTMDate>
          <xsl:value-of select="/xsdLocal:OrderRequest/xsdLocal:OrderEntry-Orders/xsdLocal:RCRMExpectedTRTMDate"/>
        </comt:expectedTRTMDate>
        <comt:orderOwner>
          <xsl:value-of select="/xsdLocal:OrderRequest/xsdLocal:OrderEntry-Orders/xsdLocal:OrderOwner"/>
        </comt:orderOwner>
        <comt:RCRMField1>
          <xsl:value-of select="/xsdLocal:OrderRequest/xsdLocal:OrderEntry-Orders/xsdLocal:RCRMField1"/>
        </comt:RCRMField1>
        <comt:SoldToAccountNumber>
          <xsl:value-of select="/xsdLocal:OrderRequest/xsdLocal:OrderEntry-Orders/xsdLocal:RCRMSoldToAccountNumber"/>
        </comt:SoldToAccountNumber>
        <comt:RCRMField6>
          <xsl:value-of select="/xsdLocal:OrderRequest/xsdLocal:Timestamp"/>
        </comt:RCRMField6>
        <comt:RCRMSAPConCountry>
          <xsl:value-of select="/xsdLocal:OrderRequest/xsdLocal:OrderEntry-Orders/xsdLocal:RCRMSAPConCountry"/>
        </comt:RCRMSAPConCountry>
      </ns0:orderHeader>
      <xsl:for-each select="/xsdLocal:OrderRequest/xsdLocal:OrderEntry-Orders/xsdLocal:OrderEntry-LineItems">
        <ns0:orderLineItem>
          <comt:CRMOLIId>
            <xsl:value-of select="xsdLocal:Id"/>
          </comt:CRMOLIId>
          <comt:rootItemId>
            <xsl:value-of select="xsdLocal:RootId"/>
          </comt:rootItemId>
          <comt:parentOrderItemId>
            <xsl:value-of select="xsdLocal:ParentOrderItemId"/>
          </comt:parentOrderItemId>
          <comt:actionCode>
            <xsl:value-of select="xsdLocal:ActionCode"/>
          </comt:actionCode>
          <comt:businessCase>
            <xsl:value-of select="xsdLocal:RCRMBusinessCase"/>
          </comt:businessCase>
          <comt:salesCode>
            <xsl:value-of select="xsdLocal:RCRMSalesReasonCode"/>
          </comt:salesCode>
          <comt:billToSubscriberNumber>
            <xsl:value-of select="xsdLocal:RCRMSubscriberNumber"/>
          </comt:billToSubscriberNumber>
          <comt:billToSubAccountNumber>
            <xsl:value-of select="xsdLocal:RCRMSubAccountNumber"/>
          </comt:billToSubAccountNumber>
          <comt:PLI>
            <xsl:value-of select="xsdLocal:PartNumber"/>
          </comt:PLI>
          <comt:productIntegrationId>
            <xsl:value-of select="xsdLocal:RCRMProdIntegrationId"/>
          </comt:productIntegrationId>
          <comt:permissioningSystem>
            <xsl:value-of select="xsdLocal:RCRMPermissioningSystem"/>
          </comt:permissioningSystem>
          <comt:manualPermissioningRequired>
            <xsl:value-of select="xsdLocal:RCRMManualPermissionedFlag"/>
          </comt:manualPermissioningRequired>
          <comt:AKR>
            <xsl:value-of select="xsdLocal:RCRMAKR"/>
          </comt:AKR>
          <comt:userID>
            <xsl:value-of select="xsdLocal:RCRMContactUserId"/>
          </comt:userID>
          <comt:userIDType>
            <xsl:value-of select="xsdLocal:RCRMProductLoginType"/>
          </comt:userIDType>
          <comt:userNumber>
            <xsl:value-of select="xsdLocal:RCRMContactUserNumber"/>
          </comt:userNumber>
          <comt:firstName>
            <xsl:value-of select="xsdLocal:RCRMContactFirstName"/>
          </comt:firstName>
          <comt:lastname>
            <xsl:value-of select="xsdLocal:RCRMContactLastName"/>
          </comt:lastname>
          <comt:dob>
            <xsl:value-of select="xsdLocal:RCRMContactBirthDate"/>
          </comt:dob>
          <comt:isNewUser>
            <xsl:value-of select="xsdLocal:RCRMContactIsNewUser"/>
          </comt:isNewUser>
          <comt:QUID>
            <xsl:value-of select='string("")'/>
          </comt:QUID>
          <xsl:choose>
            <xsl:when test='orcl:right-trim(xsdLocal:RCRMLIInstallDate) != ""'>
              <comt:installDate>
                <xsl:value-of select='concat(substring(xsdLocal:RCRMLIInstallDate,7.0,4.0),"-",substring(xsdLocal:RCRMLIInstallDate,1.0,2.0),"-",substring(xsdLocal:RCRMLIInstallDate,4.0,2.0))'/>
              </comt:installDate>
            </xsl:when>
            <xsl:otherwise>
              <comt:installDate>
                <xsl:value-of select="xsdLocal:RCRMLIInstallDate"/>
              </comt:installDate>
            </xsl:otherwise>
          </xsl:choose>
          <xsl:choose>
            <xsl:when test='orcl:right-trim(xsdLocal:RCRMLIRemovalDate) != ""'>
              <comt:removalDate>
                <xsl:value-of select='concat(substring(xsdLocal:RCRMLIRemovalDate,7.0,4.0),"-",substring(xsdLocal:RCRMLIRemovalDate,1.0,2.0),"-",substring(xsdLocal:RCRMLIRemovalDate,4.0,2.0))'/>
              </comt:removalDate>
            </xsl:when>
            <xsl:otherwise>
              <comt:removalDate>
                <xsl:value-of select="xsdLocal:RCRMLIRemovalDate"/>
              </comt:removalDate>
            </xsl:otherwise>
          </xsl:choose>
          <comt:discount>
            <xsl:value-of select="xsdLocal:RCRMDiscount"/>
          </comt:discount>
          <comt:specialPrice>
            <xsl:value-of select="xsdLocal:RCRMSpecialPrice"/>
          </comt:specialPrice>
          <comt:specialPriceCurr>
            <xsl:value-of select="xsdLocal:RCRMSpecialPriceCurrencyCode"/>
          </comt:specialPriceCurr>
          <xsl:choose>
            <xsl:when test='orcl:right-trim(xsdLocal:RCRMSpecialPriceRestrictionDate) != ""'>
              <comt:specialPriceRestrictionDate>
                <xsl:value-of select='concat(substring(xsdLocal:RCRMSpecialPriceRestrictionDate,7.0,4.0),"-",substring(xsdLocal:RCRMSpecialPriceRestrictionDate,1.0,2.0),"-",substring(xsdLocal:RCRMSpecialPriceRestrictionDate,4.0,2.0))'/>
              </comt:specialPriceRestrictionDate>
            </xsl:when>
            <xsl:otherwise>
              <comt:specialPriceRestrictionDate>
                <xsl:value-of select="xsdLocal:RCRMSpecialPriceRestrictionDate"/>
              </comt:specialPriceRestrictionDate>
            </xsl:otherwise>
          </xsl:choose>
          <comt:itemNumber>
            <xsl:value-of select="xsdLocal:RCRMCompassItemNumber"/>
          </comt:itemNumber>
          <xsl:choose>
            <xsl:when test='orcl:right-trim(xsdLocal:RCRMBillingStartStopDate) != ""'>
              <comt:startStopBillingDate>
                <xsl:value-of select='concat(substring(xsdLocal:RCRMBillingStartStopDate,7.0,4.0),"-",substring(xsdLocal:RCRMBillingStartStopDate,1.0,2.0),"-",substring(xsdLocal:RCRMBillingStartStopDate,4.0,2.0))'/>
              </comt:startStopBillingDate>
            </xsl:when>
            <xsl:otherwise>
              <comt:startStopBillingDate>
                <xsl:value-of select="xsdLocal:RCRMBillingStartStopDate"/>
              </comt:startStopBillingDate>
            </xsl:otherwise>
          </xsl:choose>
          <comt:billingType>
            <xsl:value-of select="concat(xsdLocal:RCRMPriceListRevenueType,xsdLocal:RCRMCreditDebit)"/>
          </comt:billingType>
          <comt:billingNote>
            <xsl:value-of select="xsdLocal:RCRMBillingNote"/>
          </comt:billingNote>
          <comt:freeTrailFlag>
            <xsl:value-of select="xsdLocal:RCRMFreeTrialFlag"/>
          </comt:freeTrailFlag>
          <xsl:choose>
            <xsl:when test='orcl:right-trim(xsdLocal:RCRMFreeTrialEndDate) != ""'>
              <comt:freeTrailEndDate>
                <xsl:value-of select='concat(substring(xsdLocal:RCRMFreeTrialEndDate,7.0,4.0),"-",substring(xsdLocal:RCRMFreeTrialEndDate,1.0,2.0),"-",substring(xsdLocal:RCRMFreeTrialEndDate,4.0,2.0))'/>
              </comt:freeTrailEndDate>
            </xsl:when>
            <xsl:otherwise>
              <comt:freeTrailEndDate>
                <xsl:value-of select="xsdLocal:RCRMFreeTrialEndDate"/>
              </comt:freeTrailEndDate>
            </xsl:otherwise>
          </xsl:choose>
          <comt:STB>
            <xsl:value-of select="xsdLocal:RCRMSTB"/>
          </comt:STB>
          <comt:assetIntegrationId>
            <xsl:value-of select="xsdLocal:AssetIntegrationId"/>
          </comt:assetIntegrationId>
          <comt:orderLineStatus>
            <xsl:value-of select="xsdLocal:Status"/>
          </comt:orderLineStatus>
          <comt:permissioningStatus>
            <xsl:value-of select="xsdLocal:RCRMFulfilmentStatus"/>
          </comt:permissioningStatus>
          <comt:interfaceForBilling>
            <xsl:value-of select="xsdLocal:RCRMBillingIntegrationFlag"/>
          </comt:interfaceForBilling>
          <comt:interfaceForFulfilment>
            <xsl:value-of select="xsdLocal:RCRMFulfilmentIntegrationFlag"/>
          </comt:interfaceForFulfilment>
          <xsl:for-each select="xsdLocal:OrderEntry-LineItemsAttribute">
            <comt:configuredAttribute>
              <comt:attributeName>
                <xsl:value-of select="xsdLocal:Name"/>
              </comt:attributeName>
              <comt:value>
                <xsl:value-of select="xsdLocal:Value"/>
              </comt:value>
              <comt:attributeIntegrationId>
                <xsl:value-of select="xsdLocal:XAId"/>
              </comt:attributeIntegrationId>
              <comt:valueIntegrationId>
                <xsl:value-of select='string("")'/>
              </comt:valueIntegrationId>
            </comt:configuredAttribute>
          </xsl:for-each>
          <comt:technicalFulfilmentReq>
            <xsl:value-of select="xsdLocal:RCRMTechnicalFulfilmentReq"/>
          </comt:technicalFulfilmentReq>
          <comt:technicalApprovalReq>
            <xsl:value-of select="xsdLocal:RCRMTechnicalApprovalReq"/>
          </comt:technicalApprovalReq>
          <comt:fulfilmentStatus>
            <xsl:value-of select="xsdLocal:RCRMFulfilmentStatus"/>
          </comt:fulfilmentStatus>
          <comt:fulfilmentIntegrationFlag>
            <xsl:value-of select="xsdLocal:RCRMFulfilmentIntegrationFlag"/>
          </comt:fulfilmentIntegrationFlag>
          <comt:billingAccountId>
            <xsl:value-of select="xsdLocal:RCRMBillingAccount"/>
          </comt:billingAccountId>
          <!--<comt:billingIntegrationFlag>
            <xsl:value-of select="xsdLocal:RCRMBillingIntegrationFlag"/>
          </comt:billingIntegrationFlag>-->
          <comt:technicalFulfilmentFlag>
            <xsl:value-of select="xsdLocal:RCRMTechnicalFulfilmentFlag"/>
          </comt:technicalFulfilmentFlag>
          <comt:quantity>
            <xsl:value-of select="xsdLocal:Quantity"/>
          </comt:quantity>
          <comt:product>
            <xsl:value-of select="xsdLocal:Product"/>
          </comt:product>
          <comt:altInstalBillingId>
            <xsl:value-of select="xsdLocal:AltInstalBillingId"/>
          </comt:altInstalBillingId>
          <comt:freeTrialDuration>
            <xsl:value-of select="xsdLocal:RCRMFreeTrialDuration"/>
          </comt:freeTrialDuration>
          <comt:freeTrialStartDate>
            <xsl:value-of select="xsdLocal:RCRMFreeTrialStartDate"/>
          </comt:freeTrialStartDate>
          <xsl:choose>
            <xsl:when test='orcl:right-trim(xsdLocal:RCRMLastUpdateDate) != ""'>
              <comt:lastUpdateDate>
                <xsl:value-of select='concat(substring(xsdLocal:RCRMLastUpdateDate,7.0,4.0),"-",substring(xsdLocal:RCRMLastUpdateDate,1.0,2.0),"-",substring(xsdLocal:RCRMLastUpdateDate,4.0,2.0),"T",substring(xsdLocal:RCRMLastUpdateDate,12.0))'/>
              </comt:lastUpdateDate>
            </xsl:when>
            <xsl:otherwise>
              <comt:lastUpdateDate>
                <xsl:value-of select="xsdLocal:RCRMLastUpdateDate"/>
              </comt:lastUpdateDate>
            </xsl:otherwise>
          </xsl:choose>
          <comt:mandatorytechFulfilmentFlag>
            <xsl:value-of select="xsdLocal:RCRMMandatoryTechFulfilmentFlag"/>
          </comt:mandatorytechFulfilmentFlag>
          <comt:technicalVettingFlag>
            <xsl:value-of select="xsdLocal:RCRMTechnicalVettingFlag"/>
          </comt:technicalVettingFlag>
          <comt:WorkPhone>
            <xsl:value-of select="xsdLocal:ContactWorkPhone"/>
          </comt:WorkPhone>
          <comt:ResponseCode>
            <xsl:value-of select="xsdLocal:ResponseCode"/>
          </comt:ResponseCode>
          <comt:RCRMePlatformId>
            <xsl:value-of select="xsdLocal:RCRMContactePlatformId"/>
          </comt:RCRMePlatformId>
          <comt:RCRMSupportLanguage>
            <xsl:value-of select="xsdLocal:RCRMContactSupportLanguage"/>
          </comt:RCRMSupportLanguage>
          <comt:RCRMSegGrpEndUserActivity>
            <xsl:value-of select="xsdLocal:RCRMContactSegGrpEndUserActivity"/>
          </comt:RCRMSegGrpEndUserActivity>
          <comt:RCRMRegionalFocus>
            <xsl:value-of select="xsdLocal:RCRMContactRegionalFocus"/>
          </comt:RCRMRegionalFocus>
          <xsl:choose>
            <xsl:when test='(xsdLocal:RCRMContactMarketingConsentSetDate != "") and (xsdLocal:RCRMContactMarketingConsentSetDate != "00/00/0000 00:00:00")'>
              <comt:RCRMMarketingConsentSetDate>
                <xsl:value-of select='concat(substring(xsdLocal:RCRMContactMarketingConsentSetDate,7.0,4.0),"-",substring(xsdLocal:RCRMContactMarketingConsentSetDate,1.0,2.0),"-",substring(xsdLocal:RCRMContactMarketingConsentSetDate,4.0,2.0),"T00:00:00")'/>
              </comt:RCRMMarketingConsentSetDate>
            </xsl:when>
            <xsl:otherwise>
              <comt:RCRMMarketingConsentSetDate/>
            </xsl:otherwise>
          </xsl:choose>
          <comt:RCRMManualPermissionedFlag>
            <xsl:value-of select="xsdLocal:RCRMManualPermissionedFlag"/>
          </comt:RCRMManualPermissionedFlag>
          <comt:RCRMLocalLastName>
            <xsl:value-of select="xsdLocal:RCRMContactLocalLastName"/>
          </comt:RCRMLocalLastName>
          <comt:RCRMLocalFirstName>
            <xsl:value-of select="xsdLocal:RCRMContactLocalFirstName"/>
          </comt:RCRMLocalFirstName>
          <comt:RCRMLocalDACSId>
            <xsl:value-of select="xsdLocal:RCRMContactLocalDACSId"/>
          </comt:RCRMLocalDACSId>
          <xsl:choose>
            <xsl:when test='(xsdLocal:RCRMContactLegalConsentSetDate != "") and (xsdLocal:RCRMContactLegalConsentSetDate != "00/00/0000 00:00:00")'>
              <comt:RCRMLegalConsentSetDate>
                <xsl:value-of select='concat(substring(xsdLocal:RCRMContactLegalConsentSetDate,7.0,4.0),"-",substring(xsdLocal:RCRMContactLegalConsentSetDate,1.0,2.0),"-",substring(xsdLocal:RCRMContactLegalConsentSetDate,4.0,2.0),"T00:00:00")'/>
              </comt:RCRMLegalConsentSetDate>
            </xsl:when>
            <xsl:otherwise>
              <comt:RCRMLegalConsentSetDate/>
            </xsl:otherwise>
          </xsl:choose>
          <comt:RCRMLegalConsent>
            <xsl:value-of select='dvm:lookupValue("oramds:/apps/EAIMetaData/dvm/CCRMCM_PublishContactRequestValidatorLegalConsentMap.dvm","SIEBEL",xsdLocal:RCRMContactLegalConsent,"EAI",xsdLocal:RCRMContactLegalConsent)'/>
          </comt:RCRMLegalConsent>
          <xsl:choose>
            <xsl:when test='(xsdLocal:RCRMContactLastUpdatedProfileDate != "") and (xsdLocal:RCRMContactLastUpdatedProfileDate != "00/00/0000 00:00:00")'>
              <comt:RCRMLastUpdatedProfileDate>
                <xsl:value-of select='concat(substring(xsdLocal:RCRMContactLastUpdatedProfileDate,7.0,4.0),"-",substring(xsdLocal:RCRMContactLastUpdatedProfileDate,1.0,2.0),"-",substring(xsdLocal:RCRMContactLastUpdatedProfileDate,4.0,2.0),"T00:00:00")'/>
              </comt:RCRMLastUpdatedProfileDate>
            </xsl:when>
            <xsl:otherwise>
              <comt:RCRMLastUpdatedProfileDate/>
            </xsl:otherwise>
          </xsl:choose>
          <xsl:choose>
            <xsl:when test='(xsdLocal:RCRMContactFTLFlagSetDate != "") and (xsdLocal:RCRMContactFTLFlagSetDate != "00/00/0000 00:00:00")'>
              <comt:RCRMFTLFlagSetDate>
                <xsl:value-of select='concat(substring(xsdLocal:RCRMContactFTLFlagSetDate,7.0,4.0),"-",substring(xsdLocal:RCRMContactFTLFlagSetDate,1.0,2.0),"-",substring(xsdLocal:RCRMContactFTLFlagSetDate,4.0,2.0),"T00:00:00")'/>
              </comt:RCRMFTLFlagSetDate>
            </xsl:when>
            <xsl:otherwise>
              <comt:RCRMFTLFlagSetDate/>
            </xsl:otherwise>
          </xsl:choose>
          <comt:RCRMFTLCompleteFlag>
            <xsl:value-of select="xsdLocal:RCRMContactFTLCompleteFlag"/>
          </comt:RCRMFTLCompleteFlag>
          <comt:RCRMErrorContext>
            <xsl:value-of select="xsdLocal:RCRMErrorContext"/>
          </comt:RCRMErrorContext>
          <comt:RCRMErrorCode>
            <xsl:value-of select="xsdLocal:RCRMErrorCode"/>
          </comt:RCRMErrorCode>
          <comt:RCRMDiscountReason>
            <xsl:value-of select="xsdLocal:RCRMDiscountReason"/>
          </comt:RCRMDiscountReason>
          <comt:RCRMDirectMarketing>
            <xsl:value-of select='dvm:lookupValue("oramds:/apps/EAIMetaData/dvm/CCRM_UpdateSiebelServiceMarketingConsentMap.dvm","SIEBEL",xsdLocal:RCRMContactDirectMarketing,"MARKETCONSENT",xsdLocal:RCRMContactDirectMarketing)'/>
          </comt:RCRMDirectMarketing>
          <comt:RCRMCPfGTempURL>
            <xsl:value-of select="xsdLocal:RCRMContactCPfGTempURL"/>
          </comt:RCRMCPfGTempURL>
          <comt:RCRMBillingAccount>
            <xsl:value-of select="xsdLocal:RCRMBillingAccount"/>
          </comt:RCRMBillingAccount>
          <comt:RCRMActionCode>
            <xsl:value-of select="xsdLocal:RCRMContactActionCode"/>
          </comt:RCRMActionCode>
          <xsl:choose>
            <xsl:when test='(xsdLocal:RCRMContactAAAUpdatedProfileDate != "") and (xsdLocal:RCRMContactAAAUpdatedProfileDate != "00/00/0000 00:00:00")'>
              <comt:RCRMAAAUpdatedProfileDate>
                <xsl:value-of select='concat(substring(xsdLocal:RCRMContactAAAUpdatedProfileDate,7.0,4.0),"-",substring(xsdLocal:RCRMContactAAAUpdatedProfileDate,1.0,2.0),"-",substring(xsdLocal:RCRMContactAAAUpdatedProfileDate,4.0,2.0),"T00:00:00")'/>
              </comt:RCRMAAAUpdatedProfileDate>
            </xsl:when>
            <xsl:otherwise>
              <comt:RCRMAAAUpdatedProfileDate/>
            </xsl:otherwise>
          </xsl:choose>
          <comt:PrimaryAccountId>
            <xsl:value-of select="xsdLocal:ContactPrimaryAccountId"/>
          </comt:PrimaryAccountId>
          <comt:ParentOrderItemId>
            <xsl:value-of select="xsdLocal:ParentOrderItemId"/>
          </comt:ParentOrderItemId>
          <comt:ModId>
            <xsl:value-of select="xsdLocal:ModId"/>
          </comt:ModId>
          <comt:MM>
            <xsl:value-of select="xsdLocal:ContactMM"/>
          </comt:MM>
          <comt:EmailAddress>
            <xsl:value-of select="xsdLocal:ContactEmailAddress"/>
          </comt:EmailAddress>
          <comt:ILA>
            <xsl:value-of select="xsdLocal:RCRMILA"/>
          </comt:ILA>
          <comt:contactMarketFocus>
            <xsl:value-of select="xsdLocal:RCRMContactMarketFocus"/>
          </comt:contactMarketFocus>
          <comt:billingPlatform>
            <xsl:value-of select="xsdLocal:RCRMBillingPlatform"/>
          </comt:billingPlatform>
          <comt:MxPDBName>
            <xsl:value-of select="xsdLocal:RCRMMxPDBName"/>
          </comt:MxPDBName>
          <comt:umbrellaProductIntegrationId>
            <xsl:value-of select="xsdLocal:RCRMUmbrellaProdIntId"/>
          </comt:umbrellaProductIntegrationId>
          <comt:contactReutersMessagingId>
            <xsl:value-of select="xsdLocal:RCRMContactReutersMessagingId"/>
          </comt:contactReutersMessagingId>
          <comt:oldContactUserId>
            <xsl:value-of select="xsdLocal:RCRMOldContactUserId"/>
          </comt:oldContactUserId>
          <comt:CpfgErrorMessage>
            <xsl:value-of select="xsdLocal:RCRMCpfgErrorMessage"/>
          </comt:CpfgErrorMessage>
          <comt:installSubscriberNumber>
            <xsl:value-of select="xsdLocal:InstallSubscriberNumber"/>
          </comt:installSubscriberNumber>
          <comt:installSubscriberAccountId>
            <xsl:value-of select="xsdLocal:InstallSubscriberAccountId"/>
          </comt:installSubscriberAccountId>
          <comt:installSubAccountNumber>
            <xsl:value-of select="xsdLocal:InstallSubAccountNumber"/>
          </comt:installSubAccountNumber>
          <comt:installLocationAccountId>
            <xsl:value-of select="xsdLocal:InstallLocationAccountId"/>
          </comt:installLocationAccountId>
          <comt:ContactId>
            <xsl:value-of select="xsdLocal:RCRMField4"/>
          </comt:ContactId>
          <comt:userGroup>
            <xsl:value-of select="xsdLocal:RCRMUserGroup"/>
          </comt:userGroup>
          <comt:userDomain>
            <xsl:value-of select="xsdLocal:RCRMUserDomain"/>
          </comt:userDomain>
          <comt:serverId>
            <xsl:value-of select="xsdLocal:RCRMServerId"/>
          </comt:serverId>
          <comt:contactJobFunction>
            <xsl:value-of select="xsdLocal:RCRMContactJobFunction"/>
          </comt:contactJobFunction>
          <comt:contactAnonymityReason>
            <xsl:value-of select="xsdLocal:RCRMContactAnonymityReason"/>
          </comt:contactAnonymityReason>
          <comt:contactAnonymityFlag>
            <xsl:value-of select="xsdLocal:RCRMContactAnonymityFlag"/>
          </comt:contactAnonymityFlag>
          <comt:isDelete>
            <xsl:value-of select="xsdLocal:RCRMField7"/>
          </comt:isDelete>
          <!-- Issue with Siebel Schema removing the extra elements 08/04/2011, Ram instructed to comment -->
          <!--<comt:netPriceDisplay>
            <xsl:value-of select="xsdLocal:RCRMNetPriceDisplay"/>
          </comt:netPriceDisplay>-->
          <comt:creditDebit>
            <xsl:value-of select="xsdLocal:RCRMCreditDebit"/>
          </comt:creditDebit>
          <comt:SAPBillable>
            <xsl:value-of select="xsdLocal:SAPBillable"/>
          </comt:SAPBillable>
          <comt:SAPItemNumber>
            <xsl:value-of select="xsdLocal:RCRMSAPItemNumber"/>
          </comt:SAPItemNumber>
          <comt:PONumber>
            <xsl:value-of select="xsdLocal:RCRMPONumber"/>
          </comt:PONumber>
          <comt:InstallLocationAccountNumber>
            <xsl:value-of select="xsdLocal:InstallLocationAccountNumber"/>
          </comt:InstallLocationAccountNumber>
          <comt:BillToAccountNumber>
            <xsl:value-of select="xsdLocal:BillToAccountNumber"/>
          </comt:BillToAccountNumber>
          <comt:RCRMField2>
            <xsl:value-of select="xsdLocal:RCRMField2"/>
          </comt:RCRMField2>
          <comt:RCRMField3>
            <xsl:value-of select="xsdLocal:RCRMField3"/>
          </comt:RCRMField3>
          <comt:SAPOrderNumber>
            <xsl:value-of select="xsdLocal:RCRMSAPOrderNumber"/>
          </comt:SAPOrderNumber>
          <comt:RCRMField6>
            <xsl:value-of select="xsdLocal:RCRMField6"/>
          </comt:RCRMField6>
          <comt:RCRMField1>
            <xsl:value-of select="xsdLocal:RCRMField1"/>
          </comt:RCRMField1>
          <comt:RCRMField10>
            <xsl:value-of select="xsdLocal:ReqLicenceType"/>
          </comt:RCRMField10>
          <comt:SAPActionCode>
            <xsl:value-of select="xsdLocal:RCRMSAPActionCode"/>
          </comt:SAPActionCode>
          <comt:SAPBusinessCase>
            <xsl:value-of select="xsdLocal:RCRMSAPBusinessCase"/>
          </comt:SAPBusinessCase>
          <comt:CalculatedListPrice>
            <xsl:value-of select="xsdLocal:RCRMCalculatedListPrice"/>
          </comt:CalculatedListPrice>
          <comt:ListPrice>
            <xsl:value-of select="xsdLocal:ListPrice"/>
          </comt:ListPrice>
          <comt:BillingPeriod>
            <xsl:value-of select="xsdLocal:RCRMBillingPeriod"/>
          </comt:BillingPeriod>
          <comt:PublishContactToSAP>
            <xsl:value-of select="xsdLocal:RCRMPublishContactToSAP"/>
          </comt:PublishContactToSAP>
          <comt:ContactStatus>
            <xsl:value-of select="xsdLocal:RCRMContactStatus"/>
          </comt:ContactStatus>
          <comt:PPLId>
            <xsl:value-of select="xsdLocal:RCRMPPLId"/>
          </comt:PPLId>
          <comt:primaryUUID>
            <xsl:value-of select="xsdLocal:RCRMPrimaryContactUUID"/>
          </comt:primaryUUID>
        </ns0:orderLineItem>
      </xsl:for-each>
    </ns0:orderRequest>
  </xsl:template>
</xsl:stylesheet>
