<?binding.jca UpdateCSValidationMessage_mq.jca?>
<definitions name="UpdateCSValidationMessage"
             targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/mq/headerUpdateCSValidationMessage/"
             xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:hdr="http://xmlns.oracle.com/pcbpel/adapter/mq/header"
             xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/mq/headerUpdateCSValidationMessage/"
             xmlns:imp1="http://www.siebel.com/xml/RCRM%20Order%20Entry"
             xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
             xmlns:nxsd="http://xmlns.oracle.com/pcbpel/nxsd"
             nxsd:encoding="UTF-8">
    <plt:partnerLinkType name="Enqueue_plt">
        <plt:role name="Enqueue_role">
            <plt:portType name="tns:Enqueue_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://www.siebel.com/xml/RCRM%20Order%20Entry"
                    schemaLocation="EAI.MSG.CCRM.OM.148_OrderRequest.xsd"/>
        </schema>
    </types>
    <message name="OrderRequest_msg">
        <part name="OrderRequest" element="imp1:OrderRequest"/>
    </message>
    <portType name="Enqueue_ptt">
        <operation name="Enqueue">
            <input message="tns:OrderRequest_msg"/>
        </operation>
    </portType>
</definitions>




